
# Dockerfile

# Node Version
FROM node:10-alpine

# Set working directory of docker image
WORKDIR '/var/www/app'

# Copy this root folder to docker image working directory
COPY . .


# RUN mkdir -p /usr/src/app
# WORKDIR /usr/src/app
# COPY package.json /usr/src/app/
# RUN npm install
# COPY . /usr/src/app
# EXPOSE 3000
# CMD [ “npm”, “start” ]